name = "PkgA"
uuid = "c2e99331-eab2-4a40-b7e7-63a7077ec9a6"
authors = ["Arthur Lui <luiarthur@gmail.com>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[compat]
Distributions = "0.25"
