name: PkgA-CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.julia-version == 'nightly' }}
    strategy:
      matrix:
        julia-version: ['1.6', 'nightly']
        julia-arch: [x86]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      # Install julia (several versions).
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      # Build package. Only works with julia >= 1.6.
      - uses: julia-actions/julia-buildpkg@master
      # Run tests.
      # NOTE: This also generates data for computing code coverage statistics.
      - uses: julia-actions/julia-runtest@master
        # This is needed because PkgA is not in the root directory of the
        # repo.
        with:
          project: PkgA
      # FIXME: Get coverage.
      # - uses: julia-actions/julia-processcoverage@v1
      #   # Where to find source code (usually assumed to be in `src/`)
      #   with:
      #     directories: PkgA/src
      # - uses: codecov/codecov-action@v1
      #   with:
      #     file: lcov.info
      # - uses: julia-actions/julia-uploadcoveralls@v1
      #   env:
      #     COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
